name: CI/CD Symfony Petits Pains

on:
  push:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: PROD

    steps:
      # Configuration de PHP 8.4.1
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4.1'

      # Récupération du code
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Pull github
        run: git pull origin master

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Debug Environment Variables
        run: env

      # Load DATABASE_URL from Secrets
      - name: Export DATABASE_URL
        run: echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> $GITHUB_ENV

      # Export des variables d'environnement depuis les secrets
      #- name: Set environment variables
      #  env:
      #    DB_USER: ${{ secrets.DB_USER }}
      #    DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      #    DB_HOST: ${{ secrets.DB_HOST }}
      #    DB_NAME: ${{ secrets.DB_NAME }}
      #  run: |
      #    export DATABASE_URL="mysql://$DB_USER:$DB_PASSWORD@$DB_HOST/$DB_NAME"
      #    echo "DATABASE_URL=$DATABASE_URL" >> $GITHUB_ENV

      # Mise en cache des dépendances Composer
      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      # Installation des dépendances Composer
      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      # Exécution des migrations
      - name: Run Database Migrations
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: php bin/console doctrine:migrations:migrate --no-interaction

      # Déploiement du projet (transfert des fichiers)
      #- name: Deploy to server
      #  uses: appleboy/scp-action@v0.1.3
      #  with:
      #    host: ${{ secrets.DEPLOY_HOST }}
      #    username: ${{ secrets.DEPLOY_USER }}
      #    key: ${{ secrets.DEPLOY_KEY }}
      #    source: ./
      #    target: /home/lifi5526/petits-pains.af-developpement.com
          
      # Clear Cache
      - name: Clear Symfony Cache
        run: php bin/console cache:clear --env=prod
